name: Deployment The FrontEnd App On Web

on:
  push:
    branches:
      - main

jobs:
  master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy on web server
        uses: appleboy/ssh-action@master
        with:
          host: "147.182.225.44"
          username: "rana"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/leaseweb-frontend
            GIT_SSH_COMMAND='ssh -i ~/.ssh/leaseweb-frontend -o IdentitiesOnly=yes' git reset --hard
            GIT_SSH_COMMAND='ssh -i ~/.ssh/leaseweb-frontend -o IdentitiesOnly=yes' git clean -df
            GIT_SSH_COMMAND='ssh -i ~/.ssh/leaseweb-frontend -o IdentitiesOnly=yes' git fetch origin
            GIT_SSH_COMMAND='ssh -i ~/.ssh/leaseweb-frontend -o IdentitiesOnly=yes' git checkout origin/main
            npm install
            ng build
